apiVersion: v1
kind: Service
metadata:
  name: kuard
  namespace: default
spec:
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
  - IPv6
  - IPv4  
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: kuard
  type: NodePort
